/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */
plugins {
    java
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // Dependency for better UI
    implementation("com.formdev:flatlaf:3.4.1")

    // (Swing X) implementation("com.formdev:flatlaf-swingx:3.4.1")
    implementation("com.formdev:flatlaf-intellij-themes:3.4.1")

    //
    implementation (files("lib/jssc-2.9.6.jar"))
}

application {
    mainClass.set("it.unibo.Dashboard")
}
